//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace calendarMatrix
{


    public partial class _Default
    {

        /// <summary>
        /// DailyRoomsActivitiesHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::calendar_matrix.DailyRoomsActivitiesHeader DailyRoomsActivitiesHeader;

        /// <summary>
        /// DailyRoomsActivitiesMatrix control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::calendar_matrix.DailyRoomActivitiesMatrix DailyRoomsActivitiesMatrix;
    }
}
